'use client'

import { useState } from 'react'
import { ArrowRight, BarChart3, Check, ChevronDown, Database, FileSpreadsheet, GitBranch, Menu, Network, RefreshCw, Sparkles, UserRound, Users, X } from 'lucide-react'

const hrSystems = ['Workday','SAP SuccessFactors','Oracle HCM','UKG','ADP','Dayforce','Personio','HiBob','BambooHR','Rippling']
const features = [
  [Network,'Connect your organization','Bring your existing people and organization structure into Costra. Start with an HR system or a simple CSV export.'],
  [GitBranch,'Build the hierarchy automatically','Turn departments, teams, cost centers and reporting lines into a living ownership model for AI spend.'],
  [BarChart3,'Report at every level','Give executives the company view, managers their business unit and teams the detail they actually need.'],
  [UserRound,'Make ownership visible','Every cost can have an accountable owner. Drill from the company down to the team, workload or model.'],
  [Users,'Self-service for everyone','Let budget owners explore their own AI usage, costs, trends and recommendations without waiting for FinOps.'],
  [RefreshCw,'Keep everything in sync','When your organization changes, Costra can refresh the hierarchy so reporting stays aligned with reality.'],
] as const

export default function Home(){
 const [menu,setMenu]=useState(false),[faq,setFaq]=useState(0)
 return <main>
  <nav className="topnav"><a href="#top" className="brand"><span className="brandMark">C</span><span>costra</span></a><div className={`navlinks ${menu?'open':''}`}><a href="#connect">Connect</a><a href="#hierarchy">Hierarchy</a><a href="#reporting">Reporting</a><a href="#self-service">Self-service</a><a href="#faq">FAQ</a><a className="mobileCta" href="#demo">Book a demo <ArrowRight size={15}/></a></div><div className="navActions"><a className="login" href="#demo">Sign in</a><a className="navCta" href="#demo">Book a demo <ArrowRight size={15}/></a><button className="menuBtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></nav>
  <section id="top" className="hero section"><div className="heroCopy"><p className="eyebrow"><span/> AI COST INTELLIGENCE</p><h1>Connect your organization.<br/><em>Understand your AI spend.</em></h1><p className="heroText">Costra connects your people, hierarchy and AI costs into one simple reporting layer — from executive overview to individual teams.</p><div className="heroCtas"><a className="primary" href="#demo">Book a demo <ArrowRight size={16}/></a><a className="secondary" href="#connect">See how it works</a></div><div className="heroChecks"><span><Check/> HR systems</span><span><Check/> CSV import</span><span><Check/> Multi-level ownership</span></div></div><HierarchyPreview/></section>
  <section id="connect" className="section lightSection"><div className="sectionIntro compact"><div><p className="kicker">CONNECT YOUR DATA</p><h2>Start with the system<br/><span>you already have.</span></h2></div><p>Connect your existing HR platform to bring people, departments, teams and cost centers into Costra. No HR system? Upload a CSV and get started just as easily.</p></div><div className="integrationBox"><div className="integrationTop"><div><Database size={18}/><strong>Organization sources</strong></div><span>Major HR platforms + CSV</span></div><div className="systemGrid">{hrSystems.map(s=><div className="system" key={s}><span className="systemMark">{s[0]}</span>{s}<Check size={13}/></div>)}<div className="system csv"><FileSpreadsheet size={17}/><span>Upload CSV</span><ArrowRight size={14}/></div></div><div className="syncLine"><RefreshCw size={14}/><span>Sync your organization structure</span><b>Departments · Teams · Cost centers · Managers · Employees</b></div></div></section>
  <section id="hierarchy" className="section"><div className="sectionIntro"><div><p className="kicker">ORGANIZATION MAPPING</p><h2>Your hierarchy becomes<br/><span>your cost model.</span></h2></div><p>Costra maps your existing organization into a reporting structure for AI spend. No rebuilding your company structure by hand.</p></div><div className="mappingVisual"><HierarchyTree/><div className="mappingAside"><Step n="01" title="Connect" text="Import your people and organization data."/><Step n="02" title="Map" text="Match your hierarchy to AI spend."/><Step n="03" title="Own" text="Assign accountable owners automatically."/></div></div></section>
  <section id="reporting" className="section reportingSection"><div className="centerIntro"><p className="kicker">REPORTING LAYER</p><h2>One dataset.<br/><span>Every view your business needs.</span></h2><p>Costra changes the reporting layer depending on who is looking — without creating separate spreadsheets for every stakeholder.</p></div><ReportingVisual/></section>
  <section id="self-service" className="section selfService"><div className="selfGrid"><div><p className="kicker">SELF-SERVICE</p><h2>FinOps sets the model.<br/><span>Everyone gets answers.</span></h2><p>Give teams access to the level of information they own. Managers can investigate spend, compare usage and understand what changed — without becoming FinOps experts.</p><ul className="checkList"><li><Check/> Personal and team-level views</li><li><Check/> Drill-down from company to workload</li><li><Check/> Usage, cost and trend context</li><li><Check/> Recommendations where action is needed</li></ul><a className="inlineLink" href="#demo">See self-service in action <ArrowRight size={15}/></a></div><SelfServiceVisual/></div></section>
  <section className="section featureSection"><div className="centerIntro"><p className="kicker">THE PLATFORM</p><h2>Everything around<br/><span>ownership and visibility.</span></h2></div><div className="featureGrid">{features.map(([Icon,title,text])=><article className="featureCard" key={title}><div className="featureIcon"><Icon/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section id="faq" className="section faq"><div><p className="kicker">FAQ</p><h2>Questions teams ask<br/><span>before they start.</span></h2></div><div className="faqList">{['Which HR systems can Costra connect to?','Can we start with a CSV?','Can different teams see different levels of detail?','Does Costra replace our HR system?'].map((q,i)=><div className="faqItem" key={q}><button onClick={()=>setFaq(faq===i?-1:i)}><strong>{q}</strong><ChevronDown className={faq===i?'rotated':''}/></button>{faq===i&&<p>{i===0?'Costra is designed around major enterprise and mid-market HR platforms including Workday, SAP SuccessFactors, Oracle HCM, UKG, ADP, Dayforce, Personio, HiBob, BambooHR and Rippling.':i===1?'Yes. A structured CSV can be used when an HR connector is not available or when you simply want to test the organization model first.':i===2?'Yes. Costra is designed around role-aware reporting, so executives, managers, budget owners and teams can each see the information relevant to them.':'No. Your HR system remains the source of truth for people and organization data. Costra uses that structure to create the ownership and reporting layer around AI spend.'}</p>}</div>)}</div></section>
  <section id="demo" className="cta section"><p className="kicker">SEE IT FOR YOURSELF</p><h2>Turn your organization<br/><span>into a cost graph.</span></h2><p>See how Costra can connect your hierarchy, AI spend and reporting in one place.</p><a className="primary" href="mailto:hello@costra.ai?subject=Costra%20demo">Book a demo <ArrowRight size={17}/></a></section>
  <footer><a href="#top" className="brand"><span className="brandMark">C</span><span>costra</span></a><p>AI cost intelligence for modern enterprises.</p><div><a href="#connect">Connect</a><a href="#hierarchy">Hierarchy</a><a href="#reporting">Reporting</a><a href="#self-service">Self-service</a></div><small>© 2026 Costra</small></footer>
 </main>
}
function HierarchyPreview(){return <div className="heroVisual"><div className="visualChrome"><span/><span/><span/><b>Costra · Organization</b><i>Synced just now</i></div><div className="heroVisualBody"><div className="miniSidebar"><strong>costra</strong><span className="active">Organization</span><span>AI spend</span><span>Reports</span><span>Self-service</span></div><div className="orgPreview"><div className="previewTop"><div><small>ORGANIZATION</small><h3>Acme Corporation</h3></div><span><RefreshCw size={13}/> Synced</span></div><div className="previewMetrics"><div><span>People</span><b>4,821</b></div><div><span>Teams</span><b>214</b></div><div><span>AI spend</span><b>€1.24M</b></div></div><div className="previewTree"><div className="treeRoot"><Network size={14}/> Acme Corporation</div><div className="treeBranches"><div><b>Digital Products</b><span>€520K · 1,842 users</span></div><div><b>Customer Solutions</b><span>€340K · 1,203 users</span></div><div><b>IT</b><span>€180K · 774 users</span></div></div></div></div></div></div>}
function HierarchyTree(){const groups=[['Digital Products','€520K · Owner: VP Product',['Customer AI','€221K'],['ML Platform','€145K']],['Customer Solutions','€340K · Owner: Director CS',['Support AI','€154K'],['Sales AI','€88K']],['IT','€180K · Owner: CIO',['AI Platform','€96K'],['Infrastructure','€84K']]];return <div className="hierarchyTree"><div className="node rootNode"><Network size={15}/><div><b>Acme Corporation</b><small>€1.24M AI spend</small></div></div><div className="treeConnector"/><div className="treeColumns">{groups.map(g=><div key={g[0] as string}><div className="node"><Users size={14}/><div><b>{g[0]}</b><small>{g[1]}</small></div></div>{[g[2],g[3]].map((c:any[])=> <div className="childLine" key={c[0]}><span>{c[0]}</span><b>{c[1]}</b></div>)}</div>)}</div></div>}
function ReportingVisual(){return <div className="reportingVisual"><div className="reportCard executive"><div className="reportHead"><span><BarChart3 size={14}/> Executive</span><small>Company</small></div><strong>€1.24M</strong><div className="reportBar"><i/></div><div className="reportFooter"><span>+14.2% growth</span><span>94% allocated</span></div></div><div className="reportCard manager"><div className="reportHead"><span><Users size={14}/> Manager</span><small>Digital Products</small></div><div className="managerStats"><div><b>€520K</b><span>AI spend</span></div><div><b>37</b><span>workloads</span></div><div><b>€82K</b><span>opportunity</span></div></div><div className="tinyBars">{[1,2,3,4,5,6,7].map(x=><i key={x}/>)}</div></div><div className="reportCard team"><div className="reportHead"><span><UserRound size={14}/> Team</span><small>Customer AI</small></div><div className="teamCost"><b>€221K</b><span>this month</span></div><div className="teamRows"><span>GPT-5 <b>€86K</b></span><span>Claude <b>€61K</b></span><span>Azure <b>€42K</b></span></div></div></div>}
function SelfServiceVisual(){return <div className="selfVisual"><div className="selfTop"><span>My AI spend</span><small>September · Team view</small></div><div className="selfValue"><span>Total cost</span><strong>€48,240</strong><b>↓ 8.4%</b></div><div className="selfChart"><svg viewBox="0 0 500 130" preserveAspectRatio="none"><path d="M0 98 C50 88 70 94 108 75 S170 82 205 67 S250 69 294 47 S345 61 385 36 S440 42 500 12" fill="none" stroke="currentColor" strokeWidth="3"/></svg></div><div className="selfActions"><span>Export</span><span><Sparkles size={13}/> 3 recommendations</span></div></div>}
function Step({n,title,text}:{n:string,title:string,text:string}){return <div className="mappingStep"><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></div>}
