'use client'

import { useState } from 'react'
import { ArrowRight, BarChart3, Check, ChevronDown, Database, FileSpreadsheet, GitBranch, Menu, Network, RefreshCw, Sparkles, UserRound, Users, X } from 'lucide-react'

const hrSystems = ['Workday','SAP SuccessFactors','Oracle HCM','UKG','ADP','Dayforce','Personio','HiBob','BambooHR','Rippling','Paylocity','Paycom','Gusto']
const features = [
  [Network,'Connect your organization','Bring your existing people and organization structure into Costra. Start with an HR system or a simple CSV export.'],
  [GitBranch,'Build the hierarchy automatically','Turn departments, teams, cost centers and reporting lines into a living ownership model for AI spend.'],
  [BarChart3,'Report at every level','Give executives the company view, managers their business unit and teams the detail they actually need.'],
  [UserRound,'Make ownership visible','Every cost can have an accountable owner. Drill from the company down to the team, workload or model.'],
  [Users,'Self-service for everyone','Let budget owners explore their own AI usage, costs, trends and recommendations without waiting for FinOps.'],
  [RefreshCw,'Keep everything in sync','When your organization changes, Costra can refresh the hierarchy so reporting stays aligned with reality.'],
] as const

type HierarchyGroup = [string, string, [string, string], [string, string]]

export default function Home(){
 const [menu,setMenu]=useState(false),[faq,setFaq]=useState(0)
 return <main>
  <nav className="topnav"><a href="#top" className="brand"><span className="brandMark">C</span><span>costra</span></a><div className={`navlinks ${menu?'open':''}`}><a href="#connect">Connect</a><a href="#hierarchy">Hierarchy</a><a href="#reporting">Reporting</a><a href="#self-service">Self-service</a><a href="#faq">FAQ</a><a className="mobileCta" href="#demo">Book a demo <ArrowRight size={15}/></a></div><div className="navActions"><a className="login" href="#demo">Sign in</a><a className="navCta" href="#demo">Book a demo <ArrowRight size={15}/></a><button className="menuBtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></nav>
  <section id="top" className="hero section"><div className="heroCopy"><p className="eyebrow"><span/> AI COST INTELLIGENCE</p><h1>Connect your organization.<br/><em>Understand your AI spend.</em></h1><p className="heroText">Costra connects your people, hierarchy and AI costs into one simple reporting layer — from executive overview to individual teams.</p><div className="heroCtas"><a className="primary" href="#demo">Book a demo <ArrowRight size={16}/></a><a className="secondary" href="#connect">See how it works</a></div><div className="heroChecks"><span><Check/> HR systems</span><span><Check/> CSV import</span><span><Check/> Multi-level ownership</span></div></div><HierarchyPreview/></section>
  <section id="connect" className="section lightSection"><div className="sectionIntro compact"><div><p className="kicker">CONNECT YOUR DATA</p><h2>Start with the system<br/><span>you already have.</span></h2></div><p>Connect your existing HR platform to bring people, departments, teams and cost centers into Costra. No HR system? Upload a CSV and get started just as easily.</p></div><div className="integrationBox"><div className="integrationTop"><div><Database size={18}/><strong>Organization sources</strong></div><span>Major HR platforms + CSV</span></div><div className="systemGrid">{hrSystems.map(s=><div className="system" key={s}><span className="systemMark">{s[0]}</span>{s}<Check size={13}/></div>)}<div className="system csv"><FileSpreadsheet size={17}/><span>Upload CSV</span><ArrowRight size={14}/></div></div><div className="syncLine"><RefreshCw size={14}/><span>Sync your organization structure</span><b>Departments · Teams · Cost centers · Managers · Employees</b></div></div></section>
  <section id="hierarchy" className="section"><div className="sectionIntro"><div><p className="kicker">ORGANIZATION MAPPING</p><h2>Your hierarchy becomes<br/><span>your cost model.</span></h2></div><p>Costra maps your existing organization into a reporting structure for AI spend. No rebuilding your company structure by hand.</p></div><div className="mappingVisual"><HierarchyTree/><div className="mappingAside"><Step n="01" title="Connect" text="Import your people and organization data."/><Step n="02" title="Map" text="Match your hierarchy to AI spend."/><Step n="03" title="Own" text="Assign accountable owners automatically."/></div></div></section>
  <section id="reporting" className="section reportingSection"><div className="centerIntro"><p className="kicker">REPORTING LAYER</p><h2>One dataset.<br/><span>Every view your business needs.</span></h2><p>Costra changes the reporting layer depending on who is looking — without creating separate spreadsheets for every stakeholder.</p></div><ReportingVisual/></section>
  <section id="self-service" className="section selfService"><div className="centerIntro selfIntro"><p className="kicker">SELF-SERVICE</p><h2>The right view<br/><span>for every role.</span></h2><p>Developers see their own AI behavior. Managers see how their teams perform and where a small nudge can change the outcome.</p></div><RoleScreens/></section>
  <section className="section featureSection"><div className="centerIntro"><p className="kicker">THE PLATFORM</p><h2>Everything around<br/><span>ownership and visibility.</span></h2></div><div className="featureGrid">{features.map(([Icon,title,text])=><article className="featureCard" key={title}><div className="featureIcon"><Icon/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section id="faq" className="section faq"><div><p className="kicker">FAQ</p><h2>Questions teams ask<br/><span>before they start.</span></h2></div><div className="faqList">{['Which HR systems can Costra connect to?','Can we start with a CSV?','Can different teams see different levels of detail?','Does Costra replace our HR system?'].map((q,i)=><div className="faqItem" key={q}><button onClick={()=>setFaq(faq===i?-1:i)}><strong>{q}</strong><ChevronDown className={faq===i?'rotated':''}/></button>{faq===i&&<p>{i===0?'Costra is designed around major enterprise and mid-market HR platforms including Workday, SAP SuccessFactors, Oracle HCM, UKG, ADP, Dayforce, Personio, HiBob, BambooHR, Rippling, Paylocity, Paycom and Gusto.':i===1?'Yes. A structured CSV can be used when an HR connector is not available or when you simply want to test the organization model first.':i===2?'Yes. Costra is designed around role-aware reporting, so executives, managers, budget owners and teams can each see the information relevant to them.':'No. Your HR system remains the source of truth for people and organization data. Costra uses that structure to create the ownership and reporting layer around AI spend.'}</p>}</div>)}</div></section>
  <section id="demo" className="cta section"><p className="kicker">SEE IT FOR YOURSELF</p><h2>Turn your organization<br/><span>into a cost graph.</span></h2><p>See how Costra can connect your hierarchy, AI spend and reporting in one place.</p><a className="primary" href="mailto:hello@costra.ai?subject=Costra%20demo">Book a demo <ArrowRight size={17}/></a></section>
  <footer><a href="#top" className="brand"><span className="brandMark">C</span><span>costra</span></a><p>AI cost intelligence for modern enterprises.</p><div><a href="#connect">Connect</a><a href="#hierarchy">Hierarchy</a><a href="#reporting">Reporting</a><a href="#self-service">Self-service</a></div><small>© 2026 Costra</small></footer>
 </main>
}
function HierarchyPreview(){return <div className="heroVisual"><div className="visualChrome"><span/><span/><span/><b>Costra · Organization</b><i>Synced just now</i></div><div className="heroVisualBody"><div className="miniSidebar"><strong>costra</strong><span className="active">Organization</span><span>AI spend</span><span>Reports</span><span>Self-service</span></div><div className="orgPreview"><div className="previewTop"><div><small>ORGANIZATION</small><h3>Acme Corporation</h3></div><span><RefreshCw size={13}/> Synced</span></div><div className="previewMetrics"><div><span>People</span><b>4,821</b></div><div><span>Teams</span><b>214</b></div><div><span>AI spend</span><b>€1.24M</b></div></div><div className="previewTree"><div className="treeRoot"><Network size={14}/> Acme Corporation</div><div className="treeBranches"><div><b>Digital Products</b><span>€520K · 1,842 users</span></div><div><b>Customer Solutions</b><span>€340K · 1,203 users</span></div><div><b>IT</b><span>€180K · 774 users</span></div></div></div></div></div></div>}
function HierarchyTree(){const groups: HierarchyGroup[]=[['Digital Products','€520K · Owner: VP Product',['Customer AI','€221K'],['ML Platform','€145K']],['Customer Solutions','€340K · Owner: Director CS',['Support AI','€154K'],['Sales AI','€88K']],['IT','€180K · Owner: CIO',['AI Platform','€96K'],['Infrastructure','€84K']]];return <div className="hierarchyTree"><div className="node rootNode"><Network size={15}/><div><b>Acme Corporation</b><small>€1.24M AI spend</small></div></div><div className="treeConnector"/><div className="treeColumns">{groups.map(g=><div key={g[0]}><div className="node"><Users size={14}/><div><b>{g[0]}</b><small>{g[1]}</small></div></div>{[g[2],g[3]].map(c=> <div className="childLine" key={c[0]}><span>{c[0]}</span><b>{c[1]}</b></div>)}</div>)}</div></div>}
function ReportingVisual(){return <div className="reportingVisual"><div className="reportCard executive"><div className="reportHead"><span><BarChart3 size={14}/> Executive</span><small>Company</small></div><strong>€1.24M</strong><div className="reportBar"><i/></div><div className="reportFooter"><span>+14.2% growth</span><span>94% allocated</span></div></div><div className="reportCard manager"><div className="reportHead"><span><Users size={14}/> Manager</span><small>Digital Products</small></div><div className="managerStats"><div><b>€520K</b><span>AI spend</span></div><div><b>37</b><span>workloads</span></div><div><b>€82K</b><span>opportunity</span></div></div><div className="tinyBars">{[1,2,3,4,5,6,7].map(x=><i key={x}/>)}</div></div><div className="reportCard team"><div className="reportHead"><span><UserRound size={14}/> Team</span><small>Customer AI</small></div><div className="teamCost"><b>€221K</b><span>this month</span></div><div className="teamRows"><span>GPT-5 <b>€86K</b></span><span>Claude <b>€61K</b></span><span>Azure <b>€42K</b></span></div></div></div>}
function RoleScreens(){return <div className="roleScreens"><RoleScreen type="developer" icon={<span>&lt;/&gt;</span>} label="DEVELOPER" title="Understand your AI usage." text="See personal spend, model mix and trends — then act on recommendations." bullets={['Personal AI spend and usage','Model mix and usage patterns','Compare with team average','Actionable recommendations']}><DeveloperDashboard/></RoleScreen><RoleScreen type="manager" icon={<Users size={16}/>} label="TEAM MANAGER" title="See how your team performs." text="Understand team behavior, spot optimization opportunities and nudge better decisions." bullets={['Team spend and trends','Model mix by team member','Compare usage patterns','Send recommendations']}><TeamDashboard/></RoleScreen><RoleScreen type="department" icon={<BarChart3 size={16}/>} label="DEPARTMENT MANAGER" title="Guide teams with better data." text="Compare teams, identify opportunities and make targeted nudges without becoming FinOps." bullets={['Spend by team','Model mix and trends','Optimization opportunities','Share targeted nudges']}><DepartmentDashboard/></RoleScreen></div>}
function RoleScreen({type,icon,label,title,text,bullets,children}:{type:string,icon:React.ReactNode,label:string,title:string,text:string,bullets:string[],children:React.ReactNode}){return <article className={`roleScreen ${type}`}><div className="roleCopy"><div className="roleIcon">{icon}</div><p className="kicker">{label}</p><h3>{title}</h3><p>{text}</p><ul>{bullets.map(b=><li key={b}><Check size={13}/>{b}</li>)}</ul></div><div className="productShot">{children}</div></article>}
function ShotHeader({title,subtitle}:{title:string,subtitle:string}){return <div className="shotHeader"><div><b>costra</b><strong>{title}</strong><span>{subtitle}</span></div><div className="shotMeta">Last 30 days <span>MK</span></div></div>}
function MiniMetric({label,value,change}:{label:string,value:string,change?:string}){return <div className="miniMetric"><span>{label}</span><b>{value}</b>{change&&<small>{change}</small>}</div>}
function DeveloperDashboard(){return <div className="shotApp"><aside><b>costra</b><span className="selected">My usage</span><span>Compare</span><span>Recommendations</span></aside><div className="shotMain"><ShotHeader title="My AI usage" subtitle="Your personal AI spend and model mix"/><div className="metricRow"><MiniMetric label="Total spend" value="€48" change="↓ 12%"/><MiniMetric label="Requests" value="1,842" change="↓ 8%"/><MiniMetric label="Avg. cost / request" value="€0.026" change="↓ 15%"/></div><div className="shotGrid"><div className="shotCard"><b>Model mix</b><div className="donut"><i/><span>GPT-5 <strong>46%</strong></span><span>Claude <strong>28%</strong></span><span>Gemini <strong>14%</strong></span><span>Other <strong>12%</strong></span></div></div><div className="shotCard"><b>Spend over time</b><div className="spark"><i/><i/><i/><i/><i/><i/><i/></div><small>Aug 1&nbsp;&nbsp;&nbsp; Aug 15&nbsp;&nbsp;&nbsp; Aug 30</small></div><div className="shotCard recommendations"><b>Recommendations</b><span>Use Claude for analysis <small>~40% lower cost</small></span><span>Batch non-urgent requests <small>Save up to 30%</small></span><span>Remove unused tools <small>3 tools unused</small></span></div></div></div></div>}
function TeamDashboard(){return <div className="shotApp"><aside><b>costra</b><span className="selected">Team overview</span><span>Members</span><span>Usage</span><span>Recommendations</span></aside><div className="shotMain"><ShotHeader title="Design team" subtitle="8 members · AI usage"/><div className="metricRow"><MiniMetric label="Team spend" value="€12,420" change="↓ 8%"/><MiniMetric label="Avg. cost / request" value="€0.028" change="↓ 16%"/><MiniMetric label="Optimization" value="€1,840" change="opportunity"/></div><div className="shotGrid"><div className="shotCard"><b>Model mix</b><div className="donut donutTeam"><i/><span>GPT-5 <strong>38%</strong></span><span>Claude <strong>32%</strong></span><span>Gemini <strong>20%</strong></span><span>Other <strong>10%</strong></span></div></div><div className="shotCard members"><b>Team members</b><span>Sarah <strong>€2,840</strong></span><span>Jack <strong>€2,120</strong></span><span>Emma <strong>€1,980</strong></span><span>Michael <strong>€1,640</strong></span><span>Others <strong>€3,840</strong></span></div><div className="shotCard recommendations"><b>Nudges to share</b><span>Try Claude for long-form tasks <small>~30% lower cost</small></span><span>Batch non-urgent requests <small>Reduce peak usage</small></span><span>Review unused tools <small>3 members affected</small></span></div></div></div></div>}
function DepartmentDashboard(){return <div className="shotApp"><aside><b>costra</b><span className="selected">Department</span><span>Teams</span><span>Workloads</span><span>Recommendations</span></aside><div className="shotMain"><ShotHeader title="Engineering" subtitle="AI spend across 8 teams"/><div className="metricRow"><MiniMetric label="Total spend" value="€312,400" change="↓ 18%"/><MiniMetric label="Active users" value="143" change="↑ 6%"/><MiniMetric label="Optimization potential" value="€62,800" change="20% of spend"/></div><div className="shotGrid"><div className="shotCard teamTable"><b>Team performance</b><span>Platform <strong>€98,200&nbsp;&nbsp; ↓22%</strong></span><span>Product <strong>€86,120&nbsp;&nbsp; ↓14%</strong></span><span>Data <strong>€54,300&nbsp;&nbsp; ↑6%</strong></span><span>Infrastructure <strong>€42,800&nbsp;&nbsp; ↓8%</strong></span><span>Security <strong>€31,400&nbsp;&nbsp; ↓11%</strong></span></div><div className="shotCard bars"><b>Model mix by team</b><div className="barSet"><i/><i/><i/><i/><i/></div></div><div className="shotCard recommendations"><b>Nudge your teams</b><span>Platform team <small>High GPT-5 usage · suggest lower-cost model</small></span><span>Data team <small>Spend increasing 24% · review usage</small></span><span>Infrastructure <small>Good progress · 15% reduction this month</small></span></div></div></div></div>}
function Step({n,title,text}:{n:string,title:string,text:string}){return <div className="mappingStep"><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></div>}
